# Generated by Django 4.2.7 on 2026-06-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Log your progress, TRAP notes, learnings"
            ),
        ),
    ]
