services:
  - type: web
    name: lifeflow-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
