# Generated by Django 5.1.4 on 2026-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_display_name_user_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="day_end_time",
            field=models.TimeField(default="23:00:00"),
        ),
        migrations.AddField(
            model_name="user",
            name="day_start_time",
            field=models.TimeField(default="09:00:00"),
        ),
    ]
