# Generated by Django 5.1.4 on 2026-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_day_end_time_user_day_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_processed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
